# Generated by Django 5.1.7 on 2025-03-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='preset_images/default.jpg', upload_to='preset_images/')),
                ('file', models.FileField(help_text='Upload an .xmp file', upload_to='preset_files/')),
            ],
        ),
    ]
