# Generated by Django 5.1.7 on 2025-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='price',
        ),
        migrations.AddField(
            model_name='preset',
            name='image',
            field=models.ImageField(default='preset_images/default.jpg', upload_to='preset_images/'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='file',
            field=models.FileField(help_text='Upload an .xmp file', upload_to='preset_files/'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
