# Generated by Django 5.1.7 on 2025-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0002_remove_preset_created_at_remove_preset_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='preset_images/'),
        ),
    ]
