# Generated by Django 5.1.7 on 2025-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0003_alter_preset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='image',
            field=models.ImageField(default='preset_images/default.jpg', upload_to='preset_images/'),
        ),
    ]
